openapi: 3.0.1
info:
  title: GitHub Repo Info Plugin
  description: A plugin that allows the user to fetch GitHub repository information and file contents using ChatGPT.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /repository_info/{username}/{repo_name}:
    get:
      operationId: getRepositoryInfo
      summary: Get repository information
      parameters:
      - in: path
        name: username
        schema:
            type: string
        required: true
        description: The username of the repository owner.
      - in: path
        name: repo_name
        schema:
            type: string
        required: true
        description: The name of the Github repository.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositoryInfo'
  /repository_file_contents/{repo_name}/{file_path}:
    get:
      operationId: getRepositoryFileContents
      summary: Get the contents of a file in the repository
      parameters:
      - in: path
        name: repo_name
        schema:
            type: string
        required: true
        description: The name of the Github repository (format-- user/repo).
      - in: path
        name: file_path
        schema:
            type: string
        required: true
        description: The path of the file within the repository.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileContents'
  /generate_auth_url:
    get:
      operationId: generateAuthURL
      summary: Generate a unique URL for user authentication
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  auth_url:
                    type: string
                    description: The unique URL for user authentication.

components:
  schemas:
    RepositoryInfo:
      type: object
      properties:
        name:
          type: string
          description: The name of the repository.
        owner:
          type: string
          description: The owner of the repository.
        description:
          type: string
          description: A brief description of the repository.
        stars:
          type: integer
          description: The number of stars the repository has received.
        forks:
          type: integer
          description: The number of times the repository has been forked.
    FileContents:
      type: object
      properties:
        content:
          type: string
          description: The contents of the file in the repository.
    AuthUrl:
      type: object
      properties:
        content:
          type: string
          description: The Auth URL that the user needs so that we can access their github repos
